#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &

#xsetroot -cursor_name left_ptr
#sxhkd -c ~./config/sxhkd/sxhkdrc &
# picom --experimental-backend &
# polybar example &

# Start the autostart script
~/.config/bspwm/autostart.sh &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0 

bspc config border_width         2
bspc config window_gap          0

bspc config split_ratio          0.62
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chrome desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
