#! /usr/bin/bash


#### COMMON

# terminal emulator
super + Return
	alacritty

# program launcher
super + d
	dmenu_run

# File manager
super + n
	spacefm

super + shift + Delete: Return
	google-chrome-stable

# lock screen
super + l
	xlock -mode xjack

# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

# quit/restart bspwm
super + alt + ctrl + {q,r}
	bspc {quit,wm -r}

# Close
super + shift + q
	bspc node -c

# Kill
super + shift + ctrl + q
	bspc node -k

#### WINDOW HANDLING

# set the window state
super + {t,s,f}
	bspc node -t {tiled,floating,fullscreen}

# set the node flags
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

# focus the node in the given direction
super + {_,shift + }{Left,Down,Up,Right}
	bspc node -{f,s} {west,south,north,east}

# focus the next/previous window in the current desktop
super + {_,shift + }c
	bspc node -f {next,prev}.local.!hidden.window

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
	bspc desktop -f {prev,next}.local

# focus the last node/desktop
super + {grave,Tab}
	bspc {node,desktop} -f last

# focus to given desktop
super + {1-9,0}
	bspc desktop -f '^{1-9,10}'

# send to given desktop (and focus there)
super + shift + {1-9,0}
	bspc node -d '^{1-9,10}' -f


#### PRESELECT

# preselect the direction
super + ctrl + {Left,Down,Up,Right}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
	bspc node -p cancel


#### MOVE/RESIZE

# # expand a window by moving one of its side outward
# super + alt + {Left,Down,Up,Right}
# 	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# # contract a window by moving one of its side inward
# super + alt + shift + {Left,Down,Up,Right}
# 	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# # move a floating window
# super + {Left,Down,Up,Right}
# 	bspc node -v {-20 0,0 20,0 -20,20 0}


#### APPLICATIONS

# Open browser(Chrome)
super + b
	zen-browser

# Flamehot (screenshot)
super + p
	flameshot gui

# VSCode
super + v
	code

#### UTILITY

# Change keyboard combination
super + alt + k
	~/Projects/Scripts/change-keyboard-set.sh

# Obsidian
super + o
	obsidian

# Whatsapp
super + w
	whatsapp-desktop-client


#### MEDIA

super + XF86MonBrightness{Up,Down}
	redshift -O {5500K,7500K}

# super + XF86MonBrightnessUp
# redshift -O 7500K

super + XF86AudioMicMute
	redshift -x


XF86MonBrightness{Up,Down}
	brightnessctl s 20{+,-}

XF86Audio{Raise,Lower}Volume
	pulsemixer --change-volume {+,-}5

XF86AudioMute
	pulsemixer --toggle-mute

# Bluetooth selector - select from preexisting bluetooth devices
super + alt + b
	~/Projects/Scripts/bluetooth-connect.sh

# disconnect from bluetooth device
super + alt + ctrl + b
	bluetoothctl disconnect

# Toggle audio device between bluetooth and speakers
super + XF86AudioMute 
	~/Projects/Scripts/toggle-audio-output.sh


