[colors]
  [colors.primary]
    background = '#1e1e1e'  # Dark background
    foreground = '#D1DCFB'  # Light gray text

  [colors.normal]
    black   = '#000000'
    red     = '#FD033E'  # #FFC0CB
    green   = '#F200FF'  #
    yellow  = '#ffff00'
    blue    = '#FF00EA'
    magenta = '#8a2be2'  # Purple
    cyan    = '#FF00FB'
    white   = '#ffffff'

  [colors.bright]
    black   = '#6B799F'
    red     = '#FD033E'  # Bright pink
    green   = '#EE00FF'
    yellow  = '#ffff55'
    blue    = '#9B06FE'
    magenta = '#8a2be2'  # Bright purple
    cyan    = '#FF00FB'
    white   = '#ffffff'

[window]
  opacity= 0.8

[font]
  normal = { family = "monospace", style = "Regular" }
  size = 10

